/* This file was generated by syncqt. */
#ifndef QT_QT3DCORE_VERSION_H
#define QT_QT3DCORE_VERSION_H

#define QT3DCORE_VERSION_STR "5.12.8"

#define QT3DCORE_VERSION 0x050C08

#endif // QT_QT3DCORE_VERSION_H
